# Generated by Django 4.2.20 on 2025-04-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Off-brand', max_length=50),
        ),
    ]
