# Generated by Django 4.2.20 on 2025-04-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='ads/')),
                ('link', models.CharField(help_text='Enter a relative URL like /products/3/', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
