# Generated by Django 4.2.20 on 2025-04-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_ad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
